import os
import json
import time
from pathlib import Path
from dotenv import load_dotenv
from github import Github
from message_bus import MessageBus
from google import genai


class EngineerAgent:
    def __init__(self, bus: MessageBus):
        self.bus = bus
        self.name = "Engineer"
        load_dotenv()
        self.model = os.getenv("GEMINI_MODEL", "gemini-3.1-flash-lite-preview")

    def _call_gemini(self, prompt):
        for attempt in range(3):
            try:
                client = genai.Client()
                response = client.models.generate_content(
                    model=self.model,
                    contents=prompt
                )
                if response.text:
                    return response.text.strip()
            except Exception as e:
                print(f"Gemini error (Engineer attempt {attempt+1}):", e)
                time.sleep(2 ** attempt)
        return ""

    def process_task(self):
        messages = self.bus.get_messages_for_agent(self.name)
        if not messages:
            return None

        latest_task = messages[-1]
        startup_idea = latest_task["payload"].get("startup_idea", "FAST BookSwap")

        prompt = f"""
You are a frontend engineer.

Startup:
{startup_idea}

Generate a COMPLETE HTML landing page including:
- headline
- subheadline
- features section (3 items)
- CTA button
- basic CSS styling

Return ONLY valid HTML.
"""

        html_content = self._call_gemini(prompt)

        if not html_content:
            html_content = f"""
<!DOCTYPE html>
<html>
<head>
<title>{startup_idea}</title>
</head>
<body>
<h1>{startup_idea}</h1>
<p>Campus marketplace for used books.</p>
<button>Join Waitlist</button>
</body>
</html>
"""

        Path("landing_page.html").write_text(html_content, encoding="utf-8")

        return self.bus.create_message(
            from_agent=self.name,
            to_agent="CEO",
            message_type="result",
            payload={
                "result_type": "engineering_output",
                "status": "landing_page_created",
                "details": "Landing page generated with hero section, CTA button, features list, and email capture form using LLM."
            },
            parent_message_id=latest_task["message_id"]
        )

    def handle_revision(self):
        messages = self.bus.get_messages_for_agent(self.name)

        revision_msg = None
        for msg in reversed(messages):
            if msg["message_type"] == "revision_request":
                revision_msg = msg
                break

        if not revision_msg:
            return None

        feedback = revision_msg["payload"]["revision_instruction"]

        prompt = f"""
Update the landing page HTML based on this feedback:

{feedback}

Return full updated HTML only.
"""

        updated_html = self._call_gemini(prompt)

        if updated_html:
            Path("landing_page.html").write_text(updated_html, encoding="utf-8")

        return self.bus.create_message(
            from_agent=self.name,
            to_agent="CEO",
            message_type="confirmation",
            payload={
                "result_type": "revision_completed",
                "status": "Landing page updated"
            },
            parent_message_id=revision_msg["message_id"]
        )

    def create_github_issue(self, repo):
        issue = repo.create_issue(
            title="Initial landing page",
            body="Generated by Engineer agent"
        )
        return issue.html_url

    def create_github_pr(self):
        load_dotenv()

        token = os.getenv("GITHUB_TOKEN")
        repo_name = os.getenv("GITHUB_REPO")

        g = Github(token)
        repo = g.get_repo(repo_name)

        branch = "agent-update-landing"

        try:
            repo.create_git_ref(
                ref=f"refs/heads/{branch}",
                sha=repo.get_branch("main").commit.sha
            )
        except:
            pass

        content = Path("landing_page.html").read_text()

        try:
            repo.create_file(
                "landing_page.html",
                "Agent landing page",
                content,
                branch=branch
            )
        except:
            contents = repo.get_contents("landing_page.html", ref=branch)
            repo.update_file(
                contents.path,
                "Agent landing page update",
                content,
                contents.sha,
                branch=branch
            )

        try:
            pr = repo.create_pull(
                title="Agent Landing Page",
                body="Generated by Engineer agent",
                head=branch,
                base="main"
            )
            pr_url = pr.html_url
        except Exception:
            pulls = repo.get_pulls(state='open', head=f"{repo.owner.login}:{branch}")
            pr_url = pulls[0].html_url if pulls.totalCount > 0 else "PR already exists"

        issue_url = self.create_github_issue(repo)

        return self.bus.create_message(
            from_agent=self.name,
            to_agent="CEO",
            message_type="confirmation",
            payload={
                "result_type": "github_artifacts",
                "pr_url": pr_url,
                "issue_url": issue_url
            }
        )